name: Main Action

on:
  push:
    branches: [ "main", "develop" ]

permissions:
  actions: read
  contents: read
  deployments: write
  pull-requests: write

jobs:
  build:
    name: Main job
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: nschloe/action-cached-lfs-checkout@v1

    - name: Fetch whole git history for timestamps
      run: git fetch --unshallow

    - name: restore timestamps
      uses: chetan/git-restore-mtime-action@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically

    - name: Build site
      run: make build

    - name: Link Checker
      uses: lycheeverse/lychee-action@v2
      with:
        fail: true
        args: "--base / --no-progress './_site/**/*.html'"

    - name: Deploy to Cloudflare Pages
      uses: cloudflare/wrangler-action@v3
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        command: pages deploy _site --project-name=${{ vars.CLOUDFLARE_PROJECT_NAME }}
        gitHubToken: ${{ secrets.GITHUB_TOKEN }}
